---
title: "US Power Outage Map"
output: 
  html_document:
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r load_packages, include = FALSE}
# Set repository URL
r <- getOption("repos")
r["CRAN"] <- "https://cloud.r-project.org"
options(repos = r)

# Load packages, installing as needed
if(!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
pacman::p_load(here, readr, dplyr, stringr, sf, tigris, crosstalk, DT, remotes)
pacman::p_load_gh("deohs/folders")
remotes::install_github("dmurdoch/leaflet", ref = "crosstalk4", quiet = TRUE)
pacman::p_load_gh("dmurdoch/leaflet@crosstalk4")

# Set package options
options(readr.show_col_types = FALSE, readr.show_progress = FALSE)
options(tigris_use_cache = TRUE, tigris_refresh = TRUE)
```

```{r read_config_file}
# Read config file to get default folder paths
folders <- get_folders()
data_dir <- here::here(folders$data)
```

```{r create_folders}
# Create data folder, if missing
if (!dir.exists(data_dir)) {
  dir.create(data_dir, showWarnings = FALSE, recursive = TRUE)
}
```

```{r get_outage_data}
events_csv <- file.path(data_dir, "outage_data.csv")
df_events <- read_csv(events_csv) %>% 
  mutate(fips = str_pad(fips, side = "left", width = 5, pad = "0"))
```

```{r prepare_map_data}
# Define the NA color used in the map (for filling polygons with NA events)
na_col_rgb <- list(r = '241', g = '240', b = '232')
na_col_hex <- with(na_col_rgb, rgb(r, g, b, maxColorValue = 255))

# Define the default color used in the map (for polygon borders)
def_col_hex <- '#BDBDC3'

# Get map county-level polygons
shape <- suppressMessages(
  counties(state = state.abb, progress_bar = FALSE, 
           cb = TRUE, resolution = '20m')) %>%
  st_as_sf() %>% st_transform('+proj=longlat +datum=WGS84')

# Combine outage data with FIPS codes by state and county name
df_map <- fips_codes %>% filter(state %in% state.abb) %>% 
  mutate(fips = paste0(state_code, county_code)) %>%
  left_join(df_events, by = c('fips'), multiple = "all") %>% 
  select(fips, 'State' = state_name, 'County' = county, 
         'Years' = n_years_available, 'Events' = total_8_hour_outages)

# Combine map data with outage data by FIPS code
shape <- shape %>% mutate(fips = paste0(STATEFP, COUNTYFP)) %>%
  left_join(df_map, by = c('fips'), multiple = "all") %>%
  select(State, County, Years, Events, geometry) %>%
  arrange(State, County)

# # Create a color palette
# mypal <- colorNumeric(palette = "YlOrRd", domain = shape$Events,
#                       na.color = na_col_hex)

# Convert Events to a factor with quantile-based bins to make a palette
event_probs <- c(0, 0.5, .75, .85, .90, .95, .98, .999, 1)
event_levels <- round(quantile(shape$Events, event_probs, na.rm = TRUE))
df_labels <- tibble(x = lag(event_levels, n = 1) + 1, y = event_levels) %>%
  mutate(x = ifelse(is.na(x), 0, x)) %>% 
  mutate(label = ifelse(x == y, as.character(x), paste(x, y, sep = "-")))
names(event_levels) <- df_labels$label
shape$EventsFct <- cut(shape$Events, breaks = c(-1, event_levels), 
                       labels = names(event_levels), ordered_result = TRUE)

# Compare Events with EventsFct using table() to check results
#table(shape$Events, useNA = 'always')
#table(shape$EventsFct, useNA = 'always')

# Create a color palette from a factor variable for filling counties
mypal <- colorFactor(palette = "RdYlGn", domain = shape$EventsFct, 
                     na.color = na_col_hex, reverse = TRUE)

# Wrap data frame in SharedData object for Crosstalk
sd <- SharedData$new(shape)
```

## US Counties

```{r show_map}
# Show an interactive leaflet map
bscols(
  leaflet(sd) %>% 
    addProviderTiles("OpenStreetMap.Mapnik") %>%
  setView(lat = 37.8283, lng = -98.5795, zoom = 4) %>%
  addPolygons(
    data = sd, weight = 1, color = def_col_hex, smoothFactor = 0.2, 
    fillOpacity = 0.6, fillColor = ~ mypal(EventsFct), label = ~ County, 
    popup = ~ paste("<strong>", "# of Years of Data: ", "</strong>", Years, "<br>",
                    "<strong>", "State: ", "</strong>", State, "<br>",
                    "<strong>", "County: ", "</strong>", County, "<br>",
                    "<strong>", "Events: ", "</strong>", Events, "<br>")) %>%
  # addLegend(na.label = "NA", position = "bottomleft", pal = mypal, 
  #           values = ~ Events, title = "Annual average outages", 
  #           opacity = 0.8),
  addLegend(na.label = "NA", position = "bottomleft", pal = mypal,
            values = ~ EventsFct, title = "Annual<br>average<br>outages", 
            opacity = 0.8),
  widths = c(10)                 # Maximum width of a bscols() row is 12
)
```

```{r show_filters}
# Show check boxes for Years
bscols(
  filter_checkbox("YearsFilter", "# of Years of Data", sd, group = ~ Years,
                  inline = TRUE),
  widths = c(6)
)

# Show search boxes for the state and county
bscols(
  filter_select(id = "StateFilter", label = "State", sharedData = sd, 
                group = ~ State, multiple = TRUE),
  filter_select(id = "CountyFilter", label = "County", sharedData = sd, 
                group = ~ County, multiple = TRUE),
  widths = c(5, 5)
)
```

```{r show_table, warning=FALSE}
# Show data as interactive table
bscols(
  datatable(sd, 
            colnames = c("State" = "State", "County" = "County", 
                         "# of Years of Data" = "Years", 
                         "Annual average outages" = "Events"),
            extensions = "Scroller", style = "bootstrap", class = "stripe",
            width = "100%", height = "45%", rownames = FALSE,
            options = list(
              deferRender = TRUE, scrollY = 250, scroller = TRUE, 
              dom = 'ltipr', searching = TRUE,
              columnDefs = list(list(visible = TRUE, targets = c(0, 1, 2, 3)),
                                list(visible = FALSE, targets = '_all')))),
  widths = c(10)
)
```

- Source code: https://github.com/brianhigh/jacasey_power_outages
